### ISSUE TITLE
Networking lesson references third-party content (youtube video)

### ISSUE THREAD

**Issue by P33M** [raspberrypilearning/networking-lessons#10]
http://www.raspberrypi.org/learning/networking-lessons/lesson-1/README.md

references

http://www.youtube.com/watch?v=kNJZ-v263zc

as a primer.

What happens when the owner of the video
a) deletes their account
b) removes the video
c) makes the video private?

**Comment by clivebeale** [comment]
We'll find a new one. Online resources in lesson plans chop and change -- it's one of the things you deal with as a teacher without breaking stride :)
