### ISSUE TITLE
Update to new format

### ISSUE THREAD

**Issue by lauraclay** [raspberrypilearning/networking-lessons#11]
- [x] cover.png
- [x] LICENCE.md
- [x] CONTRIBUTING.md
- [x] meta.yml
- [x] hardware.yml
- [x] software.yml
- [x] extras.yml
- [x] overview.md
- [x] learn.md
- [x] lesson.md
- [x] ks.md

**Comment by bennuttall** [comment]
We have a cover, will be added when ready for new format

**Comment by bennuttall** [comment]
Lesson names are missing from `meta.yml`

**Comment by LornaLynch** [comment]
Cover image is still needed.

**Comment by LornaLynch** [comment]
I've created software.md and software.yml, but I haven't populated them as I am not sure of the correct commands in terminal to install the resources. @bennuttall, can you help?

**Comment by bennuttall** [comment]
- hardware.yml refers to images in the components repo
- hardware.md is optional if extra information is needed (rare)
- It's not clear to me what the software requirements are as I didn't write the resource
- cover.png will be added last (it's what stops the resource being rendered in the new template before it's ready)
- Lesson plans needs to follow the template
- Random other markdown files need moving into the lesson plan or student worksheet

**Comment by LornaLynch** [comment]
Thank you! 
- I didn't know about the Components repo: will get onto that right now. 
- Will delete hardware.md
- @davidhoness @clivebeale I am trying to populate software.md and software.yml for this resource, but I don't know the correct commands in terminal to install the resources. As I believe you have written/created the Networking resource, could one of you help me? 
- Re: the lesson plans, I'll work on revising these today.
- Moving files: will do.

**Comment by bennuttall** [comment]
Look at examples of `software.yml` and `software.md` in other resources - although this is slightly different as they're not packages, just files - I'd just put a reference to them in software.yml and move the `wget` instructions for these files into `software.md`

**Comment by LornaLynch** [comment]
I'll do my best.

**Comment by bennuttall** [comment]
All done, this is now live in the new format.
