### ISSUE TITLE
Lesson 2 missing thing-client.py ?

### ISSUE THREAD

**Issue by lurch** [raspberrypilearning/networking-lessons#12]
Looking at https://www.raspberrypi.org/learning/networking-lessons/lesson-2/worksheet/ it has the source-code for `thing-server.py` but no source-code (or download link) for the `thing-client.py` script?
(Or is it included elsewhere and I simply overlooked it?)

Elsewhere on that same page it also says "The server machine is connected to a button. It monitors data from the client machine, and when it receives a '?' character..." but the `thing-server.py` script actually looks like it listens for _any_ character that isn't a carriage-return or newline?

**Comment by lurch** [comment]
I've just spotted that https://github.com/raspberrypilearning/networking-lessons/blob/master/README.md actually says "`network.py` and `thing-client.py` copied to the SD card", but the teacher-instructions (for both Lesson1 and Lesson2) only mention `network.py` and not `thing-client.py`...

**Comment by bennuttall** [comment]
@LornaLynch has this been dealt with?

**Comment by LornaLynch** [comment]
I've been looking for any references to thing-client.py, and I haven't found anything in the teacher instructions. There are references to `python thing-server.py` and `python thing-client.py` in the student worksheet under 'Running the Program', but these are commands entered. Am I right in thinking `thing-client.py` is not something which can be copied to the SD card? @davidhoness?

**Comment by whaleygeek** [comment]
These lessons are based on some lessons that I originally designed. I had a chat with @clivebeale and said he could use them for whatever purpose he wants on RaspberryPi Learning. Some of the file names were changed I think in the re-working of the supporting materials.

But, here is my original code along with all of the challenges I designed:

https://github.com/whaleygeek/pibakeoff/tree/master/code/backup

You'll find the original lesson plan and other resources here:

https://github.com/whaleygeek/pibakeoff/tree/master/docs

**Comment by whaleygeek** [comment]
The 'thing' demonstration was based on this additional work that I did for an event. Again, I gave @clivebeale permission to do whatever he wanted with it...

http://blog.whaleygeek.co.uk/raspberry-pi-internet-of-things-demonstrator/

**Comment by lawsie** [comment]
Thing client appears to be present, so I'm closing this issue. This resource does need updating to GPIO zero though.

**Comment by lurch** [comment]
Okay, add-more-details time... (I guess I should have added this earlier)

https://github.com/raspberrypilearning/networking-lessons/blob/master/lesson-2/worksheet.md#running-the-program (also visible at https://www.raspberrypi.org/learning/networking-lessons/lesson-2/worksheet/ ) mentions running "python thing-client.py 192.168.0.2" but there's no other mentions of this file in that worksheet. https://github.com/raspberrypilearning/networking-lessons/blob/master/README.md _does_ mention "network.py and thing-client.py copied to the SD card", but unfortunately https://github.com/raspberrypilearning/networking-lessons/blob/master/software.md and https://github.com/raspberrypilearning/networking-lessons/blob/master/software.yml only mention `network.py`, and not `thing-client.py`.

So unless I've misunderstood something, IMHO this should be re-opened.

**Comment by lawsie** [comment]
Aha, thanks for the extra details. I've marked this resource for review so I will look over all of it at some point soon. Re-opening for now.

**Comment by jonwitts** [comment]
OK, so I have a working GPIOZero version of thing-server.py and thing-client.py and I am just formatting the worksheet in a branch of mine ATM. thing-client.py is a piece of code the students need to write on the remote Pi, which then runs and connects back to the server Pi.

I will get this finalised and sent over as a PR ASAP.

My question is this... I have been playing around with the remote GPIO in GPIOZero and this whole lesson can be implemented in 17 lines of code with nothing needed to be run on the client, aside from the required Remote GPIO stuff

![image](https://cloud.githubusercontent.com/assets/8962587/23592540/8d161f94-01fa-11e7-83e7-fa49944463ae.png)

My thoughts are that there is greater educational value in having students get this quicker result enabling further time for play, experimentation and discussion. I could include the Remote GPIO version as an extension task, or if people agree, I could replace this code with the Remote GPIO code and build in some further extension activities with that...

**Comment by jonwitts** [comment]
Here's the GPIOZero version of the missing thing-client.py program... 

![image](https://cloud.githubusercontent.com/assets/8962587/23592578/11215524-01fb-11e7-9b57-49e9d926b89f.png)

**Comment by whaleygeek** [comment]
In my mind, the question is, can you telnet into a GPIOzero remote pin server and send it obvious commands and interact with it raw - just like you can telnet into port 80 of any web server and send it a GET request and get a HTML web page back?

The whole point of this resource, was to teach networking 'how it works'.

The thing_client/thing_server were written to be a natural progression from learning about networking, learning about network sockets and port numbers, learning about telnet, and then layering a very simple set of applications around that learning (i.e. a chat program, and then an end to end application with some hardware).

Much as I love the work done on gpio zero, by using the remote gpio classes it doesn't seem to progress naturally from the chat client and chat server.

Note, if you write the chat server in python, then you can just use telnet as your chat client, which is a standard diagnostics tool used by all network engineers (telnet). Again, that was the whole point of this - to teach network programming, not to teach specific abstractions.

Hope that helps?

**Comment by whaleygeek** [comment]
For reference, here are the original resources that I wrote for an event that myself, Ryan and Charlotte, ran in Stevenage a few years ago: https://github.com/whaleygeek/pibakeoff

**Comment by jonwitts** [comment]
Thanks David, that helps a lot.

I am planning on teaching lesson 2 on Tuesday so was just checking code and worksheets beforehand. 

I think I will go with the GPIOZero adjusted versions of your code, using network.py and then maybe develop a separate unit of lessons around Remote GPIO when I have a little more time :-D 

Thanks,
Jon

**Comment by lawsie** [comment]
Sorry - been on holiday for a week and now am at Picademy for a couple of days. Will try to have a look at the PR at the end of this week. Many thanks! :)

**Comment by jonwitts** [comment]
That's OK @lawsie ! I have just added another one for Lesson 3 now ;-)

I will look at Lesson 4 soon and then double check the other unit resources too.

**Comment by martinohanlon** [comment]
This resource has now been archived so I am closing the issue.

@lurch @jonwitts @whaleygeek thanks for your support, these lessons are no longer accessible via the raspberrypi.org site and will ultimately be replaced by content created by the NCCE.

I will get the url https://www.raspberrypi.org/learning/networking-lessons redirected to this repo and have put a note on the README to note that it has now been archived and will no longer be maintained.
