### ISSUE TITLE
Misspelling of "Win32 Disk Imager"

### ISSUE THREAD

**Issue by lurch** [raspberrypilearning/networking-lessons#15]
Both `lesson-1/teacher-instructions.md` and `lesson-2/teacher-instructions.md` refer to "Win disk 32 imager", when it should actually be "Win32 Disk Imager".

I won't submit a PR for this, because like #13 I wonder if this also affects multiple resources, and so the whole "Making a class set of SD cards" section would be better served by linking to a 'standard URL', the way that "Instructions for best practice on [downloading and installing NOOBS can be read here](http://www.raspberrypi.org/documentation/installation/noobs.md)" does? (Or the way "To make sure your SD card is up-to-date, see the [updating Raspbian guide](http://www.raspberrypi.org/documentation/raspbian/updating.md)." does on http://www.raspberrypi.org/learning/turtle-snowflakes/requirements/ ).
I guess the last section of http://www.raspberrypi.org/documentation/linux/filesystem/backup.md is currently the "nearest match" which is probably too vague as it stands currently to be directly linked-to from the learning resources.

**Comment by bennuttall** [comment]
@LornaLynch has this been fixed in copy editing?

**Comment by LornaLynch** [comment]
Yes, I've fixed it, but it's from the section we were considering cutting anyway (the instructions for making multiple SD cards) so it may all be academic...
