### ISSUE TITLE
Hardware.yml created, images needed

### ISSUE THREAD

**Issue by LornaLynch** [raspberrypilearning/networking-lessons#19]
I've created hardware.yml, and I've added the relevant names and urls. I don't have access to the images: could someone who has access add them?

**Comment by bennuttall** [comment]
Images are not used in the resource repository, rather they are used as references to the [components](https://github.com/raspberrypilearning/components/tree/master/components/) repository.

**Comment by LornaLynch** [comment]
I didn't know this: thanks!

**Comment by LornaLynch** [comment]
OK: silly question... Do I need to copy the images to this repo somehow, or is it enough to just insert jumper-female-to-female.png (etc) in the .yml file?

**Comment by LornaLynch** [comment]
Additionally, there doesn't seem to be a component image for a network cable (I'm assuming this type is intended http://shop.pimoroni.com/products/cat5e-utp-ethernet-cable)
@davidhoness @clivebeale Can you confirm this is the right sort of network cable for the networking lessons? 
@samalderhyde Can you provide a component image for this cable (or for the correct kind if I have inadvertently picked the wrong one)?

**Comment by bennuttall** [comment]
> Do I need to copy the images to this repo somehow

No - just refer to the image name (without file extension) and the template sorts it out. See other resources for reference.

**Comment by bennuttall** [comment]
> Can you confirm this is the right sort of network cable for the networking lessons?

I just checked with Dave, and yes it is.

> Can you provide a component image for this cable (or for the correct kind if I have inadvertently picked the wrong one)?

I already have one from Sam - I will add to the components repo now.

Are there any other hardware items needed, or can this be closed now?

**Comment by LornaLynch** [comment]
Nothing else needed: thanks!
