### ISSUE TITLE
Lesson 1, teacher instructions

### ISSUE THREAD

**Issue by LornaLynch** [raspberrypilearning/networking-lessons#20]
This document is to do with the setting up of a batch of SD cards: it doesn't figure in the other Teach resources. As the Hardware section of the new format template contains the wording about SD cards and usual peripherals, can I safely delete this document? Or, at least, remove references to it from the lesson plan?

**Comment by bennuttall** [comment]
Yes, I would.

However, I would move the "download network.py" instructions into `software.md`.

Anything that is standard setup should be removed, anything specific to this resource should be part of the software requirements.

**Comment by LornaLynch** [comment]
Thank you: I'll move the instructions now.
