### ISSUE TITLE
location of network.py changed - obscured goo.gl link in tutorial needs updating

### ISSUE THREAD

**Issue by DeeJay** [raspberrypilearning/networking-lessons#22]
Obscured short link resolves to https://raw.githubusercontent.com/raspberrypilearning/networking-lessons/master/lesson-1/network.py

Module is now at https://raw.githubusercontent.com/raspberrypilearning/networking-lessons/master/lesson-1/code/network.py

**Comment by elParaguayo** [comment]
Link was on this page https://www.raspberrypi.org/learning/networking-lessons/requirements/software/
