### ISSUE TITLE
Broken links to Static IP guide

### ISSUE THREAD

**Issue by lurch** [raspberrypilearning/networking-lessons#24]
I'm not sure exactly where the issue lies, because when viewed on github, everything links up okay.
But when viewed via https://www.raspberrypi.org/learning/networking-lessons/lesson-1/worksheet/ the "static IP address setup guide" (linked to in two places on that page) *seems* to link to https://www.raspberrypi.org/learning/networking-lessons/lesson-1/rpi-static-ip-address.md but when you actually click on the link, it goes to https://www.raspberrypi.org/learning/networking-lessons/lesson-1/rpi-static-ip-address/ and you're left staring at a blank web-page!

The worksheet for lesson2 also has two links to that static-IP-guide, and they again work on [gituhub](https://github.com/raspberrypilearning/networking-lessons/blob/master/lesson-2/worksheet.md), but fail (in a slightly different way) when viewed directly from [raspberrypi.org](https://www.raspberrypi.org/learning/networking-lessons/lesson-2/worksheet/).

Ping @bennuttall in case this is a web-server issue.

**Comment by MarcScott** [comment]
Moved file and fixed links
