### ISSUE TITLE
Original source references to network.py and other networking resources

### ISSUE THREAD

**Issue by whaleygeek** [raspberrypilearning/networking-lessons#25]
I'm really pleased to see lots of forks and additional work taking place on the networking lessons, it's great to see others innovating.

The code and resources here I donated under a very open licence, after discussions with @clivebeale . However you might find it helpful to know where the original master of these resources live:

Here is the code, along with all chat challenges:

https://github.com/whaleygeek/pibakeoff/tree/master/code/backup

Here is the IOT demonstrator project:

http://blog.whaleygeek.co.uk/raspberry-pi-internet-of-things-demonstrator/

Here are the lesson plans and other resources

https://github.com/whaleygeek/pibakeoff/tree/master/docs

I was wondering if anyone had any objection to putting a reference to these 3 links somewhere in the material? It's just that I've been very pleased to see lots of forks and other work based on this, but I've only discovered it 'by chance'. I might be further developing these base resources in the future, and it would be nice to think that you would be able to benefit from hearing about those additions as and when they become available.

**Comment by MarcScott** [comment]
Hi @whaleygeek - I've added links to the front page

**Comment by clivebeale** [comment]
Sorry @whaleygeek -- was sure I'd included these originally!

**Comment by whaleygeek** [comment]
Thanks :)
