### ISSUE TITLE
Broken link on Static IP guide

### ISSUE THREAD

**Issue by lurch** [raspberrypilearning/networking-lessons#26]
At the bottom of the (now-fixed) https://www.raspberrypi.org/learning/networking-lessons/rpi-static-ip-address/ there's a "NEXT LESSON" button, and clicking on it leads to a 404.

**Comment by MarcScott** [comment]
@lurch You're determined to keep me busy aren't you :smile: 
@bennuttall I moved the static IP guide into the root folder as it wasn't linking properly from the worksheets. It now has an autogenerated Next Lesson link at the bottom of the sheet. Can you take a look at this one.

**Comment by lurch** [comment]
Got to keep you on your toes... ;-)

**Comment by martinohanlon** [comment]
This resource has now been archived so I am closing the issue.
