### ISSUE TITLE
Static IP guide needs updating

### ISSUE THREAD

**Issue by lurch** [raspberrypilearning/networking-lessons#27]

**Comment by lurch** [comment]
In recent versions of Raspbian, `/etc/network/interfaces` now says:
\# Please note that this file is written to be used with dhcpcd
\# For static IP, consult /etc/dhcpcd.conf and 'man dhcpcd.conf'

http://www.modmypi.com/blog/how-to-give-your-raspberry-pi-a-static-ip-address-update or http://www.jeffgeerling.com/blog/2016/setting-static-ip-address-raspbian-jessie-lite-on-raspberry-pi or https://www.raspberrypi.org/forums/viewtopic.php?f=66&t=140252 etc. show how it should be done now.

And see also https://www.raspberrypi.org/blog/another-update-raspbian/#comment-1258195

**Comment by MarcScott** [comment]
@lurch Does that look okay now?

**Comment by lurch** [comment]
I can't test right now, but I don't know if you can set the same static IP address for both `eth0` and `wlan0` ?  It's probably easier to just leave out wlan0 entirely, as this lesson is about setting up a static IP address (over ethernet) between two Raspberry Pis, and setting up an adhoc wifi network is much more involved.

And I think it'd be better to leave the previous text (about commenting out values with `#`) in place, rather than simply advising to remove the lines entirely.

I'm not sure why you changed the keyboard shortcuts to lowercase? E.g. https://github.com/raspberrypilearning/networking-lessons/blob/master/lesson-1/worksheet.md still uses uppercase keypresses.

**Comment by lurch** [comment]
(and the previous version of the guide only setup a `gateway` address - equivalent to `routers` in dehcpd.conf, and not also a DNS server address, but I dunno if that makes any difference)

**Comment by MarcScott** [comment]
Cheers. I'll go back and fix later.
I prefer lower case shortcuts as I'm an emacs user and there's a difference
between `ctrl + char` and `ctrl + shift + char`  in some modes - just a
preference. I'll go through the worksheets and edit them as well.

**Comment by lurch** [comment]
Is there / should there be something in https://github.com/raspberrypilearning/creating-resources about how to format keyboard shortcuts? @bennuttall  @lauraclay ?

**Comment by lawsie** [comment]
Is this now fixed? I tried it yesterday and it seemed fine. @MarcScott

**Comment by MarcScott** [comment]
If you tried it and it works @lawsie then I suggest we close it.

**Comment by lurch** [comment]
I still think the `wlan0` section ought to be removed. Especially as the worksheet that links to the static IP guide says "Connect the two Pis with an Ethernet cable"

**Comment by lawsie** [comment]
Yeah, I was wondering about that, it seems a little pointless to have both. I actually tested it on wireless (at home though) and it did work OK, so perhaps the static IP guide should say add either wlan0 or eth0 depending on how you're connecting them. In schools, doing it on the wifi might be a pain.

**Comment by lurch** [comment]
I'm not a networking expert, but I believe using Wifi also requires each of the Pis to be connected to a wifi router first, and the static wlan0 IP configuration will only work if the router also happens to be in the same `192.168.0.x` address-range that you're configuring. And obviously in a classroom situation you can't have multiple Pis all attempting to connect to Wifi with the static IP address `192.168.0.2` ;-)
Far too many things to go wrong, which is why I believe just a single ethernet cable between two Pis is the simplest and most robust configuration.

Ideally, this static IP configuration guide ought to be detailing how to _disable_ the wlan0 interface (if it's been previously configured), in case the wlan0 is already using the `192.168.0.x` range, which might confuse the networking stack about which interface it should be using to contact the `192.168.0.3` Pi? \*shrug\*

**Comment by epoch1970** [comment]
I wanted to direct people from the forums to this page.
Unfortunately, the same address is used on 2 different interfaces in the network in that example. 
This is fundamentally wrong.
It happens that when i. on linux, ii. using the default routing configuration, iii. if the 2 interfaces are in the same host, doing this works...

I suggest either removing one of the interfaces declarations or using 2 different IPs, e.g. .2 and .3.

**Comment by martinohanlon** [comment]
This resource has now been archived so I am closing the issue.
