### ISSUE TITLE
Lesson2 Code Review link : 404 error

### ISSUE THREAD

**Issue by bsimmo** [raspberrypilearning/networking-lessons#28]
The main website gives a 404 error on code review link. I can see it fine in here though.

https://www.raspberrypi.org/learning/networking-lessons/lesson-2/plan/

**Comment by lawsie** [comment]
@MarcScott The raspberrypi.org template doesn't pick up worksheet2.md in the teach format. Could possibly move it to the main part of the repo and link from there?

**Comment by MarcScott** [comment]
Copied to root and redid links - awaiting to see if it fixes issue
