### ISSUE TITLE
Python 2 or 3

### ISSUE THREAD

**Issue by jonwitts** [raspberrypilearning/networking-lessons#30]
I am working through these resources as I use them for my class and in lesson 1 https://github.com/raspberrypilearning/networking-lessons/blob/master/lesson-1/worksheet.md it says to run the program using python - Should we be using python3 as standard now?

I have tested it in python3 and the code works fine...

I have a pull request ready for this worksheet which changes it to using python3 amongst other things which I will submit if people agree on the change to python3...

https://github.com/jonwitts/networking-lessons/blob/jonwitts-patch-2/lesson-1/worksheet.md

**Comment by lawsie** [comment]
Hi Jon. We now use Python 3 for all resources so that should be the default. PR updating to Python 3 would be really nice! :)

**Comment by jonwitts** [comment]
PR submitted :)
