### ISSUE TITLE
No link to Network.py

### ISSUE THREAD

**Issue by BenjaminStuermer** [raspberrypilearning/networking-lessons#37]
On https://www.raspberrypi.org/learning/networking-lessons/requirements/ it is correctly noted that you'll have to download a copy of network.py, but no link is provided.

There is a link to software installation instructions: https://www.raspberrypi.org/learning/networking-lessons/requirements/software/, however that page indicates that network.py can be installed as a PIP module, which it cannot.

I think the best solution may be to remove "For information on installing these libraries, see the software installation page." from the requirements page. Instead, I would make the word "network.py" in the preceding bullet point a link to the file, and would indicate that this file needs to be saved in the same folder as the scripts to be written in the lessons.

**Comment by AmericanUmlaut** [comment]
Closing. This was a misunderstanding of an error that was preventing installation of the network package via PIP in my environment.
